name: Spotify Production Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup environment variables
        id: vars
        run: |
          echo "::set-output name=CLIENT_VERSION::${GITHUB_SHA::8}-$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Setup NodeJs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Npm Install
        run: |
          npm install
      - name: Production Build
        run: |
          echo "Client version: ${REACT_APP_CLIENT_VERSION}"
          npm run build
        env:
          REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
          REACT_APP_SPOTIFY_REDIRECT_URI: ${{ secrets.REACT_APP_SPOTIFY_REDIRECT_URI }}
          REACT_APP_CLIENT_VERSION: ${{ steps.vars.outputs.CLIENT_VERSION }}
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'build'
